import os
import tempfile

from dotenv import load_dotenv

load_dotenv()

DEBUG_MODE = os.getenv("ASKTUBE_DEBUG_MODE", "on")
APP_DIR = os.path.abspath(os.getenv("ASKTUBE_APP_DIR", os.path.join(tempfile.gettempdir(), "asktube")))
LANGUAGE_PREFER_USAGE: str = os.getenv("ASKTUBE_LANGUAGE_PREFER_USAGE", "en")
AUDIO_CHUNK_DETECT_DURATION: int = int(os.getenv("ASKTUBE_AUDIO_CHUNK_DETECT_DURATION", 30))
AUDIO_CHUNK_CHAPTER_DURATION: int = int(os.getenv("ASKTUBE_AUDIO_CHUNK_CHAPTER_DURATION", 600))
QUERY_SIMILAR_THRESHOLD: float = float(os.getenv("ASKTUBE_QUERY_SIMILAR_THRESHOLD", 0.5))

GEMINI_API_KEY = os.getenv("ASKTUBE_GEMINI_API_KEY", None)
OPENAI_API_KEY = os.getenv("ASKTUBE_OPENAI_API_KEY", None)
CLAUDE_API_KEY = os.getenv("ASKTUBE_CLAUDE_API_KEY", None)
VOYAGEAI_API_KEY = os.getenv("ASKTUBE_VOYAGEAI_API_KEY", None)
MISTRAL_API_KEY = os.getenv("ASKTUBE_MISTRAL_API_KEY", None)

EMBEDDING_PROVIDER = os.getenv("ASKTUBE_EMBEDDING_PROVIDER", "gemini")
GEMINI_EMBEDDING_MODEL = os.getenv("ASKTUBE_GEMINI_EMBEDDING_MODEL", "models/text-embedding-004")
OPENAI_EMBEDDING_MODEL = os.getenv("ASKTUBE_OPENAI_EMBEDDING_MODEL", "text-embedding-ada-002")
VOYAGEAI_EMBEDDING_MODEL = os.getenv("ASKTUBE_VOYAGEAI_EMBEDDING_MODEL", "voyage-large-2")
MISTRAL_EMBEDDING_MODEL = os.getenv("ASKTUBE_MISTRAL_EMBEDDING_MODEL", "mistral-embed")

LOCAL_EMBEDDING_MODEL = os.getenv("ASKTUBE_LOCAL_EMBEDDING_MODEL", "intfloat/multilingual-e5-base")
LOCAL_EMBEDDING_DEVICE = os.getenv("ASKTUBE_LOCAL_EMBEDDING_DEVICE", "cpu")

LOCAL_WHISPER_MODEL = os.getenv("ASKTUBE_LOCAL_WHISPER_MODEL", "base")
LOCAL_WHISPER_DEVICE = os.getenv("ASKTUBE_LOCAL_WHISPER_DEVICE", "cpu")

LOCAL_OLLAMA_HOST = os.getenv("ASKTUBE_LOCAL_OLLAMA_HOST", "http://localhost:11434")
LOCAL_OLLAMA_MODEL = os.getenv("ASKTUBE_LOCAL_OLLAMA_MODEL", "qwen2")
