networks:
  asktube-net:
    internal: false
    enable_ipv6: false

volumes:
  llm-data:
  engine-data:

services:
  proxy:
    image: traefik:v2.11
    container_name: proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      # - "--providers.docker.exposedbydefault=false"
      # - "--entrypoints.traefik.address=:8080"
      # - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      # - "--entrypoints.websecure.http.tls=false"
      # - "--log.level=DEBUG"
    networks:
      - asktube-net
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - llm-data:/root/.ollama
    networks:
      - asktube-net
  engine:
    image: ifelsedotone/asktube-engine:latest
    container_name: engine
    restart: unless-stopped
    environment:
      - AT_LOCAL_OLLAMA_HOST=http://ollama:11434
      - AT_LOCAL_OLLAMA_MODEL=qwen2
      - AT_LOCAL_EMBEDDING_MODEL=intfloat/multilingual-e5-base
      - AT_LOCAL_EMBEDDING_DEVICE=cpu
      - AT_LOCAL_WHISPER_MODEL=base
      - AT_LOCAL_WHISPER_DEVICE=cpu
    volumes:
      - engine-data:/var/asktube
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.engine.loadbalancer.server.port=8000"
      - "traefik.http.routers.engine-route.entrypoints=web"
      - "traefik.http.routers.engine-route.service=engine"
      - "traefik.http.routers.engine-route.rule=PathPrefix(`/api`)"
      - "traefik.http.middlewares.engine-block-management.replacepathregex.regex=^/(.*)"
      - "traefik.http.middlewares.engine-block-management.replacepathregex.replacement=/api/$1"
    networks:
      - asktube-net
  web:
    image: ifelsedotone/asktube-web:latest
    container_name: web
    restart: unless-stopped
    networks:
      - asktube-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.asktube-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.asktube-web-route.entrypoints=asktube-web"
      - "traefik.http.routers.asktube-web-route.service=asktube-web"
      - "traefik.http.routers.asktube-web-route.rule=PathPrefix(`/`)"
